name: Playground

on:
  push:
  workflow_dispatch:

jobs:
  run-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check Environment
        uses: TLizer/github-actions-playground/actions/first-action@main